# AdaBoost
hyperparameters:
- name: estimator
  default_value: "DecisionTreeRegressor"
  type: categorical
  choices:
  - "DecisionTreeRegressor"
  - "Ridge"
# - name: n_estimators
#   default_value: 50
#   type: uniform_int
#   lower: 10
#   upper: 500
- name: learning_rate
  default_value: 1.0
  type: uniform_float
  lower: 0.0001
  upper: 2.0
  log: true
- name: loss
  default_value: "linear"
  type: categorical
  choices:
  - "linear"
  - "square"
  - "exponential"
