# BayesianRidge
hyperparameters:
- name: alpha_1
  default_value: 0.000001
  type: uniform_float
  log: true
  lower: 0.0000001
  upper: 10
- name: alpha_2
  default_value: 0.000001
  type: uniform_float
  log: true
  lower: 0.0000001
  upper: 10
- name: lambda_1
  default_value: 0.000001
  type: uniform_float
  log: true
  lower: 0.0000001
  upper: 10
- name: lambda_2
  default_value: 0.000001
  type: uniform_float
  log: true
  lower: 0.0000001
  upper: 10
- name: alpha_init
  default_value: 1.0
  type: uniform_float
  log: true
  lower: 0.0000001
  upper: 1000
- name: lambda_init
  default_value: 1.0
  type: uniform_float
  log: true
  lower: 0.0000001
  upper: 1000