hyperparameters:
- name: learning_rate
  default_value: 0.05
  type: uniform_float
  lower: 0.0001
  upper: 0.3
  log: true
- name: depth
  default_value: 6
  type: uniform_int
  lower: 4
  upper: 8
- name: l2_leaf_reg
  default_value: 3.0
  type: uniform_float
  lower: 1.0
  upper: 6.0
- name: loss_function
  default_value: "RMSE"
  type: categorical
  choices:
  - "RMSE"
  - "MAE"
  - "Poisson"
  - "MAPE"
