# Huber
hyperparameters:
- name: alpha
  default_value: 0.0001
  type: uniform_float
  log: true
  lower: 0.00001
  upper: 0.1
- name: fit_intercept
  default_value: true
  type: categorical
  choices:
    - true
    - false
- name: epsilon
  default_value: 1.35
  type: uniform_float
  lower: 1.0
  upper: 10.0
- name: max_iter
  default_value: 100
  type: uniform_int
  lower: 100
  upper: 1000
