hyperparameters:
- name: n_components
  default_value: 2  
  type: uniform_int
  lower: 1
  upper: 8
- name: scale
  default_value: true
  type: categorical
  choices:
    - true
    - false
- name: max_iter
  default_value: 500
  type: uniform_int
  lower: 100
  upper: 10000
  log: true
- name: tol
  default_value: 0.000001
  type: uniform_float
  log: true
  lower: 0.00000001
  upper: 0.5
