hyperparameters:
- name: degree
  default_value: 1
  type: uniform_int
  lower: 1
  upper: 10
- name: fit_intercept
  default_value: true
  type: categorical
  choices:
    - true
    - false
- name: positive
  default_value: false
  type: categorical
  choices:
    - true
    - false