hyperparameters:
- name: criterion
  default_value: "squared_error"
  type: categorical
  choices:
  - "squared_error"
  - "absolute_error"
  - "poisson"
  - "friedman_mse"
- name: min_samples_split
  default_value: 2
  type: uniform_int
  lower: 2
  upper: 20
- name: max_features
  default_value: 0.5
  type: uniform_float
  lower: 0.1
  upper: 0.5
