hyperparameters:
- name: eta
  default_value: 0.1
  type: uniform_float
  lower: 0.0001
  upper: 1.0
  log: true
- name: alpha
  default_value: 0.1
  type: uniform_float
  lower: 0.000001
  upper: 2
  log: true
- name: lambda
  default_value: 1.0
  type: uniform_float
  lower: 0.000001
  upper: 2
  log: true
- name: gamma
  default_value: 0.1
  type: uniform_float
  lower: 0.000001
  upper: 64
  log: true
- name: subsample
  default_value: 1.0
  type: uniform_float
  lower: 0.5
  upper: 1.0
- name: colsample_bytree
  default_value: 1.0
  type: uniform_float
  lower: 0.3
  upper: 1.0
- name: max_depth
  default_value: 6
  type: uniform_int
  lower: 2
  upper: 8
- name: n_estimators
  default_value: 100
  type: uniform_int
  lower: 2
  upper: 10000
  log: true
- name: min_child_weight
  default_value: 1
  type: uniform_int
  lower: 1
  upper: 5