n_trials: 512 # 1000 when random
metrics:
  - mean_absolute_error
  - mean_squared_error
  - r2_score
  - mean_absolute_percentage_error
  - root_mean_squared_error
preferences:
  r2_score: -1.0 # Higher is better